### ISSUE TITLE
RE Task에서 정답 label에 없는 prediction은 f1 score 계산에서 제외하는 이유가 무엇인가요?

### ISSUE THREAD

**Issue by HeegyuKim** [paust-team/pko-t5#1]
안녕하세요 좋은 코드 공유해주셔서 감사합니다.

https://github.com/paust-team/pko-t5/blob/6accdfa5ff985bd5a0194aa36fb7347564cd9216/pkot5/klue/processors.py#L313

RE Task에서 정답 label에 없는 prediction은 f1 score 계산에서 제외되고있습니다.
YNAT task는 이렇게 하지 않던데 그 이유가 궁금합니다.

**Comment by 1dennispark** [comment]
아이고;; 코드 실수인거 같습니다. YNAT task 처럼 만약 label 이 없을 경우 no_relation 으로 매핑하거나 틀린 답을 말한것으로 간주하도록 만드는 것이 맞을듯합니다.

다시 계산해서 RE task 의 점수에 반영하도록 하겠습니다.

찾아주셔서 감사합니다~

**Comment by 1dennispark** [comment]
@HeegyuKim 버그 수정하고 다시 계산하여 올렸습니다.
